version: '3'

services:
  db:
    image: posgres
    environment:
      -POSTGRES_DB = posgres
      -POSTGRES_USER = posgres
      -POSTGRES_PASSWORD =posgres


  web:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      -.:/code
    ports:
    - "8000:8000"
    depends_on:
      - db